-- 차집합: LEFT(또는 RIGHT) OUTER JOIN + WHERE 조건 IS NULL 
SELECT ins.NAME, ins.DATETIME
FROM ANIMAL_INS AS ins
    LEFT OUTER JOIN ANIMAL_OUTS as outs 
    ON ins.ANIMAL_ID = outs.ANIMAL_ID 
WHERE outs.DATETIME IS NULL
ORDER BY ins.DATETIME
LIMIT 3;